#project information
site_name: Rebilly JS SDK
site_description: Official Rebilly JS SDK Documentation

#theme
theme:
  name: 'material'
  favicon: 'images/favicon.ico'
  palette:
    primary: 'indigo'
    accent: 'deep purple'

extra_css:
  - 'styles/extra.css'


#repo information
repo_name: 'Rebilly JS SDK'
repo_url: 'https://github.com/Rebilly/rebilly-js-sdk'

# Copyright
copyright: 'Copyright &copy; 2019 Rebilly Inc.'

#extensions
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: True
  - attr_list
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs

#page tree
nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - Reference:
    - RebillyAPI: reference/rebilly-api.md
    - RebillyExperimentalAPI: reference/rebilly-experimental-api.md
    - RebillyErrors: reference/rebilly-errors.md
    - Resources:
      - Accounts: reference/resources/account.md
      - API Keys: reference/resources/api-keys.md
      - Bank Accounts: reference/resources/bank-accounts.md
      - Blacklists: reference/resources/blacklists.md
      - Checkout Pages: reference/resources/checkout-pages.md
      - Contacts: reference/resources/contacts.md
      - Coupons: reference/resources/coupons.md
      - Credential Hashes: reference/resources/credential-hashes.md
      - Custom Events: reference/resources/custom-events.md
      - Custom Fields: reference/resources/custom-fields.md
      - Customers: reference/resources/customers.md
      - Customer Authentication: reference/resources/customer-authentication.md
      - Disputes: reference/resources/disputes.md
      - Events: reference/resources/events.md
      - Files: reference/resources/files.md
      - Gateway Accounts: reference/resources/gateway-accounts.md
      - Invoices: reference/resources/invoices.md
      - KYC Documents: reference/resources/kyc-documents.md
      - Layouts: reference/resources/layouts.md
      - Lists: reference/resources/lists.md
      - Notes: reference/resources/notes.md
      - Organizations: reference/resources/organizations.md
      - Payment Cards: reference/resources/payment-cards.md
      - Payment Tokens: reference/resources/payment-tokens.md
      - Paypal Accounts: reference/resources/paypal-accounts.md
      - Plans: reference/resources/plans.md
      - Previews: reference/resources/previews.md
      - Products: reference/resources/products.md
      - Profile: reference/resources/profile.md
      - Sessions: reference/resources/sessions.md
      - Shipping Zones: reference/resources/shipping-zones.md
      - Status: reference/resources/status.md
      - Subscriptions: reference/resources/subscriptions.md
      - Three D Secure (3DS): reference/resources/three-d-secure.md
      - Tracking: reference/resources/tracking.md
      - Transactions: reference/resources/transactions.md
      - Users: reference/resources/users.md
      - Webhooks: reference/resources/webhooks.md
      - Websites: reference/resources/websites.md
    - Experimental:
      - Customers: reference/resources/experimental/customers.md
      - Exports: reference/resources/experimental/exports.md
      - Histograms: reference/resources/experimental/histograms.md
      - Reports: reference/resources/experimental/reports.md
    - Response Types:
      - Member: reference/types/member.md
      - Collection: reference/types/collection.md
      - File: reference/types/file.md
  - Guides:
    - Criteria: guides/criteria.md
    - Filters: guides/filters.md
  - License: license.md
